In [1]:
import numpy as np

# Capacitance values (Farads)
C_q = 7.837e-14      # Qubit capacitance
C_r = 3.525e-13      # Resonator 1 capacitance
C_ls = 8.073e-13     # Resonator 2 capacitance
C_rs = 4.257e-13     # Resonator 3 capacitance

# Coupling capacitances (Farads)
C_qr = 5.181e-15     # Qubit-Resonator 1 coupling
C_qls = 1.414e-15    # Qubit-Resonator 2 coupling
C_qrs = 2.184e-15    # Qubit-Resonator 3 coupling

# Frequencies (rad/s) -- fill in your values
w_q = 3.2e9 # low freq  #MHz      # Qubit frequency
w_r = 6.73e9   # Resonator 1 frequency
w_ls = 3.01e9  # Resonator 2 frequency
w_rs = 5.8e9   # Resonator 3 frequency

alpha = 0.24e9  # Anharmonicity (example value)

# g calculations
g_qr = 0.5 * np.sqrt(w_q * C_q) * np.sqrt(w_r * C_r) * (C_qr / (C_q * C_qr + C_q * C_r + C_qr * C_r))
g_qls = 0.5 * np.sqrt(w_q * C_q) * np.sqrt(w_ls * C_ls) * (C_qls / (C_q * C_qls + C_q * C_ls + C_qls * C_ls))
g_qrs = 0.5 * np.sqrt(w_q * C_q) * np.sqrt(w_rs * C_rs) * (C_qrs / (C_q * C_qrs + C_q * C_rs + C_qrs * C_rs))

# Detunings
Delta_qr = w_q - w_r
Delta_qls = w_q - w_ls
Delta_qrs = w_q - w_rs

# chi calculations
chi_qr = (2 * g_qr**2 / Delta_qr) - (2 * g_qr**2 / (Delta_qr + alpha))
chi_qls = (2 * g_qls**2 / Delta_qls) - (2 * g_qls**2 / (Delta_qls + alpha))
chi_qrs = (2 * g_qrs**2 / Delta_qrs) - (2 * g_qrs**2 / (Delta_qrs + alpha))

print(f"g_qr = {g_qr/1e6:.3f} MHz, chi_qr = {chi_qr/1e6:.3e} Hz")
print(f"g_qls = {g_qls/1e6:.3f} MHz, chi_qls = {chi_qls:.3e} Hz")
print(f"g_qrs = {g_qrs/1e6:.3f} MHz, chi_qrs = {chi_qrs:.3e} Hz")


g_qr = 66.921 MHz, chi_qr = 1.851e-01 Hz
g_qls = 8.554 MHz, chi_qls = 4.299e+05 Hz
g_qrs = 24.934 MHz, chi_qrs = 4.863e+04 Hz


In [2]:
import numpy as np

# Capacitance values (Farads)
C_q = 7.837e-14      # Qubit capacitance
C_r = 3.525e-13      # Resonator 1 capacitance
C_ls = 8.073e-13     # Resonator 2 capacitance
C_rs = 4.257e-13     # Resonator 3 capacitance

# Coupling capacitances (Farads)
C_qr = 5.181e-15     # Qubit-Resonator 1 coupling
C_qls = 1.414e-15    # Qubit-Resonator 2 coupling
C_qrs = 2.184e-15    # Qubit-Resonator 3 coupling

# Frequencies (GHz)
f_q = 3.2e9    # Qubit frequency (GHz)
f_r = 6.73e9   # Resonator 1 frequency (GHz)
f_ls = 3.01e9  # Resonator 2 frequency (GHz)
f_rs = 5.8e9   # Resonator 3 frequency (GHz)


Ec_q = -.240  # in GHz

# eta (in MHz)
eta = Ec_q 

def calc_g_chi(C_g, C_r, f_r_GHz, label):
    beta = C_g / C_q
    g = 0.5 * beta * np.sqrt(f_q * C_q) * np.sqrt(f_r_GHz / C_r)  # MHz
    delta = (f_r_GHz  - f_q)  # MHz
    chi = 2 * (g**2 / delta) * eta / (delta + eta) * (f_r_GHz / f_q)
    print(f"{label}: g = {g:.3f} MHz, chi = {chi:.3f} MHz")
    return g, chi

g_qr, chi_qr = calc_g_chi(C_qr, C_r, f_r, "Qubit-Resonator 1")
g_qls, chi_qls = calc_g_chi(C_qls, C_ls, f_ls, "Qubit-Resonator 2")
g_qrs, chi_qrs = calc_g_chi(C_qrs, C_rs, f_rs, "Qubit-Resonator 3")

Qubit-Resonator 1: g = 72328862.292 MHz, chi = -0.000 MHz
Qubit-Resonator 2: g = 8723389.238 MHz, chi = -0.001 MHz
Qubit-Resonator 3: g = 25756383.081 MHz, chi = -0.000 MHz


In [14]:
# from Hanzhe capacitance value calcs


cr = 3.691e-13
cq = 1.157e-13
cls = 8.208e-13
crs = 4.555e-13
crq = -3.106e-15
c1q = -3.502e-15
c2q = -1.058e-15


In [41]:
c_matrix = np.array([
    [cr-crq, crq, 0, 0],
    [crq, cq-crq-c1q-c2q, c1q, c2q],
    [0, c1q, cls-c1q, 0],
    [0, c2q, 0, crs-c2q]
])


# c_matrix = np.array([
#     [cr, crq, 0, 0],
#     [crq, cq, c1q, c2q],
#     [0, c1q, cls, 0],
#     [0, c2q, 0, crs]
# ])

c_inv = np.linalg.inv(c_matrix)
print(c_inv)

[[2.68724892e+12 6.76666813e+10 2.87478033e+08 1.56806690e+08]
 [6.76666813e+10 8.10880386e+12 3.44497904e+10 1.87908535e+10]
 [2.87478033e+08 3.44497904e+10 1.21329397e+12 7.98318685e+07]
 [1.56806690e+08 1.87908535e+10 7.98318685e+07 2.19034576e+12]]


In [42]:
# constants
e = 1.602176634e-19       # elementary charge (C)
hbar = 1.054571817e-34    # reduced Planck (J s)
Z0 = 50.0                 # characteristic impedance (Ohm)
pi = np.pi
pref = e * np.sqrt(pi * hbar / (2.0 * Z0))

EC_T = 0.5 * (1.6e-19)**2 * c_inv[1, 1] / 6.63e-34 / 1e6
print(f"EC_T = {EC_T:.6f} MHz")




EC_T = 156.550059 MHz


In [17]:
C_q = cq+crq+c1q+c2q #7.837e-14 
C_qr = crq #5.181e-15
f_q = 5.3e9  # Qubit frequency in GHz
f_r = 6.73e9  # Resonator 1 frequency in GHz
beta = abs(C_qr) / C_q

g = 0.5 * beta * np.sqrt(f_q * C_q) * np.sqrt(f_r / C_r)
print(f"g_qr = {g:.3e} ")

g_qr = 4.753e+07 


In [45]:
import numpy as np

# Capacitance values (Farads)
C_q = 7.837e-14
C_r = 3.525e-13
C_ls = 8.073e-13
C_rs = 4.257e-13

# Coupling capacitances (Farads)
C_qr = 5.181e-15
C_qls = 1.414e-15
C_qrs = 2.184e-15

# Frequencies (Hz)
f_q = 3.2e9
f_r = 6.73e9
f_ls = 3.01e9
f_rs = 5.8e9

# Capacitance values (Farads)
C_q = cq
C_r = cr
C_ls = cls
C_rs = crs

# Coupling capacitances (Farads)
C_qr = -crq
C_qls = -c1q
C_qrs = -c2q

w_r = 6.75e9
w_ls = 3.0e9
w_rs = 5.5e9
wq = 5.3e9
# Frequencies (Hz)
f_q = wq
f_r = w_r
f_ls = w_ls
f_rs = w_rs


# Anharmonicity (Hz)
alpha = 0.240e9  # negative for transmon

def calc_g(C_g, C_r, f_r):
    beta = C_g / C_q
    return 0.5 * beta * np.sqrt(f_q * C_q) * np.sqrt(f_r / C_r)/1e6

def calc_chi(g, delta, alpha):
    return 2 * g**2 * alpha / (delta*(delta + alpha))

# Qubit-Resonator 1
g_qr = calc_g(C_qr, C_r, f_r)
Delta_qr = f_q - f_r
chi_qr = calc_chi(g_qr, Delta_qr, alpha)
print(f"Qubit-Resonator 1: g = {g_qr:.3f} MHz, chi = {chi_qr/1e6:.3f} MHz")

# Qubit-Resonator 2
g_qls = calc_g(C_qls, C_ls, f_ls)
Delta_qls = f_q - f_ls
chi_qls = calc_chi(g_qls, Delta_qls, alpha)
print(f"Qubit-Resonator 2: g = {g_qls:.3f} MHz, chi = {chi_qls/1e6:.3f} MHz")

# Qubit-Resonator 3
g_qrs = calc_g(C_qrs, C_rs, f_rs)
Delta_qrs = f_q - f_rs
chi_qrs = calc_chi(g_qrs, Delta_qrs, alpha)
print(f"Qubit-Resonator 3: g = {g_qrs:.5f} MHz, chi = {chi_qrs/1e6:.3f} MHz")

Qubit-Resonator 1: g = 44.949 MHz, chi = 0.000 MHz
Qubit-Resonator 2: g = 22.657 MHz, chi = 0.000 MHz
Qubit-Resonator 3: g = 12.44125 MHz, chi = -0.000 MHz


In [ ]:
# Implementation of ħ g = e * sqrt(π ħ / (2 Z0)) * Cg / (C1*Cg + C1*Cr + Cg*Cr)
import numpy as np

# given capacitances (F)
C_q  = 7.837e-14   # qubit capacitance
C_r  = 3.525e-13   # resonator 1 capacitance
C_ls = 8.073e-13
C_rs = 4.257e-13

# coupling caps (F)
C_qr  = 5.181e-15
C_qls = 1.414e-15
C_qrs = 2.184e-15

# constants
e = 1.602176634e-19       # elementary charge (C)
hbar = 1.054571817e-34    # reduced Planck (J s)
Z0 = 50.0                 # characteristic impedance (Ohm)
pi = np.pi

def g_from_caps(C1, Cg, Cr, Z0=50.0):
    denom = C1*Cg + C1*Cr + Cg*Cr
    pref = e * np.sqrt(pi * hbar / (2.0 * Z0))
    g_rad = pref * (Cg / denom) / hbar   # g in rad/s (since equation is ħ g = ...)
    g_hz = g_rad / (2*pi)
    return g_hz / 1e6  # MHz

g_qr_MHz  = g_from_caps(C_q,  C_qr,  C_r,  Z0)
g_qls_MHz = g_from_caps(C_q,  C_qls, C_ls, Z0)
g_qrs_MHz = g_from_caps(C_q,  C_qrs, C_rs, Z0)

print(f"g_qr  = {g_qr_MHz:.6f} MHz")
print(f"g_qls = {g_qls_MHz:.6f} MHz")
print(f"g_qrs = {g_qrs_MHz:.6f} MHz")
# Implementation of ħ g = e * sqrt(π ħ / (2 Z0)) * Cg / (C1*Cg + C1*Cr + Cg*Cr)
import numpy as np

# given capacitances (F)
C_q  = 7.837e-14   # qubit capacitance
C_r  = 3.525e-13   # resonator 1 capacitance
C_ls = 8.073e-13
C_rs = 4.257e-13

# coupling caps (F)
# C_qr  = 5.181e-15
# C_qls = 1.414e-15
# C_qrs = 2.184e-15


#coupling capacitance from Q3D
C_qr  = 5.181e-15
C_qls = 1.414e-15
C_qrs = 2.184e-15

# constants
e = 1.602176634e-19       # elementary charge (C)
hbar = 1.054571817e-34    # reduced Planck (J s)
Z0 = 50.0                 # characteristic impedance (Ohm)
pi = np.pi

def g_from_caps(C1, Cg, Cr, Z0=50.0):
    denom = C1*Cg + C1*Cr + Cg*Cr
    pref = e * np.sqrt(pi * hbar / (2.0 * Z0))
    g_rad = pref * (Cg / denom) / hbar   # g in rad/s (since equation is ħ g = ...)
    g_hz = g_rad / (2*pi)
    return g_hz / 1e6  # MHz

g_qr_MHz  = g_from_caps(C_q,  C_qr,  C_r,  Z0)
g_qls_MHz = g_from_caps(C_q,  C_qls, C_ls, Z0)
g_qrs_MHz = g_from_caps(C_q,  C_qrs, C_rs, Z0)

print(f"g_qr  = {g_qr_MHz:.6f} MHz")
print(f"g_qls = {g_qls_MHz:.6f} MHz")
print(f"g_qrs = {g_qrs_MHz:.6f} MHz")

g_qr  = 76.370163 MHz
g_qls = 9.645383 MHz
g_qrs = 27.891185 MHz
g_qr  = 76.370163 MHz
g_qls = 9.645383 MHz
g_qrs = 27.891185 MHz


In [ ]:
# hanzhe 2CV1DV

import scqubits as scq
import qutip as qt
import numpy as np
# device / transmon / resonator params (GHz)
wq_GHz = 5.3
wr_GHz = 6.75
w_ls_GHz = 3.0
w_rs_GHz = 5.5
EC = 0.16
EJ = 22.5
# --- Use g values directly (MHz) - edit these as needed ---
g_qr_MHz  = 45.0
g_qls_MHz = 22.5
g_qrs_MHz = 12.5
def compute_chi_for_resonator(wr_here_GHz, g_MHz, label):
    g_GHz = g_MHz / 1e3
    # build systems
    tmon = scq.Transmon(EJ=EJ, EC=EC, ng=0, ncut=41, truncated_dim=10)
    resonator = scq.Oscillator(E_osc=wr_here_GHz, truncated_dim=20)
    hs = scq.HilbertSpace([tmon, resonator])
    # add interaction using g directly (scqubits expects g in GHz)
    g_pref = 1j * g_GHz
    hs.add_interaction(
        expr="g * n * a - g * n * adag",
        op1=("n", tmon.n_operator),
        op2=("adag", resonator.creation_operator),
        op3=("a", resonator.annihilation_operator),
        add_hc=False,
    )
    hs.generate_lookup()
    # exact (numerical) chi via diagonalization
    evals = hs["evals"][0]
    diag_dressed_hamiltonian = 2 * np.pi * qt.Qobj(np.diag(evals), dims=[hs.subsystem_dims] * 2)
    def truncate(operator: qt.Qobj, dimension: int) -> qt.Qobj:
        return qt.Qobj(operator[:dimension, :dimension])
    diag_trunc = truncate(diag_dressed_hamiltonian, 10)
    evalues_GHz = (diag_trunc.eigenenergies() - diag_trunc.eigenenergies()[0]) / (2 * np.pi)  # GHz
    e_11 = evalues_GHz[hs.dressed_index((1,1))]
    e_10 = evalues_GHz[hs.dressed_index((1,0))]
    e_01 = evalues_GHz[hs.dressed_index((0,1))]
    e_00 = evalues_GHz[hs.dressed_index((0,0))]
    chi_exact_GHz = e_11 - e_10 - e_01 + e_00
    # perturbative dispersive chi (transmon formula)
    Delta_GHz = wq_GHz - wr_here_GHz
    alpha_GHz = -EC
    chi_pert_GHz = 2 * (g_GHz**2) * alpha_GHz / (Delta_GHz * (Delta_GHz + alpha_GHz))
    print(f"\n{label}: g = {g_MHz:.3f} MHz | Exact chi = {chi_exact_GHz*1e3:.4f} MHz | Pert chi = {chi_pert_GHz*1e3:.4f} MHz")
    print(f"  Energies (GHz) e11,e10,e01,e00 = {e_11:.6f}, {e_10:.6f}, {e_01:.6f}, {e_00:.6f}")
    print(f"  Δ = {Delta_GHz:.6f} GHz, α = {alpha_GHz:.6f} GHz")
    return chi_exact_GHz, chi_pert_GHz
# compute for all three resonators
chi_qr_exact, chi_qr_pert = compute_chi_for_resonator(wr_GHz, g_qr_MHz, "Resonator 1 (wr)")
chi_qls_exact, chi_qls_pert = compute_chi_for_resonator(w_ls_GHz, g_qls_MHz, "Resonator 2 (w_ls)")
chi_qrs_exact, chi_qrs_pert = compute_chi_for_resonator(w_rs_GHz, g_qrs_MHz, "Resonator 3 (w_rs)")
# relative differences
def rel_diff(exact, pert):
    return (exact - pert) / (exact if exact != 0 else 1.0)
print(f"\nRelative diffs (pert vs exact): Res1={rel_diff(chi_qr_exact,chi_qr_pert):.3f}, Res2={rel_diff(chi_qls_exact,chi_qls_pert):.3f}, Res3={rel_diff(chi_qrs_exact,chi_qrs_pert):.3f}")
# ...existing code...
# filepath: /Users/tanvirahmedmasum/Documents/Coding/Circuit Quantization/Transmon chi calc from g value.ipynb
# ...existing code...
import scqubits as scq
import qutip as qt
import numpy as np
# device / transmon / resonator params (GHz)
wq_GHz = 5.3
wr_GHz = 6.75
w_ls_GHz = 3.0
w_rs_GHz = 5.5
EC = 0.16
EJ = 22.5
# --- Use g values directly (MHz) - edit these as needed ---
g_qr_MHz  = 45.0
g_qls_MHz = 22.5
g_qrs_MHz = 12.5
def compute_chi_for_resonator(wr_here_GHz, g_MHz, label):
    g_GHz = g_MHz / 1e3
    # build systems
    tmon = scq.Transmon(EJ=EJ, EC=EC, ng=0, ncut=41, truncated_dim=10)
    resonator = scq.Oscillator(E_osc=wr_here_GHz, truncated_dim=20)
    hs = scq.HilbertSpace([tmon, resonator])
    # add interaction using g directly (scqubits expects g in GHz)
    g_pref = 1j * g_GHz
    hs.add_interaction(
        expr="g * n * a - g * n * adag",
        op1=("n", tmon.n_operator),
        op2=("adag", resonator.creation_operator),
        op3=("a", resonator.annihilation_operator),
        add_hc=False,
    )
    hs.generate_lookup()
    # exact (numerical) chi via diagonalization
    evals = hs["evals"][0]
    diag_dressed_hamiltonian = 2 * np.pi * qt.Qobj(np.diag(evals), dims=[hs.subsystem_dims] * 2)
    def truncate(operator: qt.Qobj, dimension: int) -> qt.Qobj:
        return qt.Qobj(operator[:dimension, :dimension])
    diag_trunc = truncate(diag_dressed_hamiltonian, 10)
    evalues_GHz = (diag_trunc.eigenenergies() - diag_trunc.eigenenergies()[0]) / (2 * np.pi)  # GHz
    e_11 = evalues_GHz[hs.dressed_index((1,1))]
    e_10 = evalues_GHz[hs.dressed_index((1,0))]
    e_01 = evalues_GHz[hs.dressed_index((0,1))]
    e_00 = evalues_GHz[hs.dressed_index((0,0))]
    chi_exact_GHz = e_11 - e_10 - e_01 + e_00
    # perturbative dispersive chi (transmon formula)
    Delta_GHz = wq_GHz - wr_here_GHz
    alpha_GHz = -EC
    chi_pert_GHz = 2 * (g_GHz**2) * alpha_GHz / (Delta_GHz * (Delta_GHz + alpha_GHz))
    print(f"\n{label}: g = {g_MHz:.3f} MHz | Exact chi = {chi_exact_GHz*1e3:.4f} MHz | Pert chi = {chi_pert_GHz*1e3:.4f} MHz")
    print(f"  Energies (GHz) e11,e10,e01,e00 = {e_11:.6f}, {e_10:.6f}, {e_01:.6f}, {e_00:.6f}")
    print(f"  Δ = {Delta_GHz:.6f} GHz, α = {alpha_GHz:.6f} GHz")
    return chi_exact_GHz, chi_pert_GHz
# compute for all three resonators
chi_qr_exact, chi_qr_pert = compute_chi_for_resonator(wr_GHz, g_qr_MHz, "Resonator 1 (wr)")
chi_qls_exact, chi_qls_pert = compute_chi_for_resonator(w_ls_GHz, g_qls_MHz, "Resonator 2 (w_ls)")
chi_qrs_exact, chi_qrs_pert = compute_chi_for_resonator(w_rs_GHz, g_qrs_MHz, "Resonator 3 (w_rs)")
# relative differences
def rel_diff(exact, pert):
    return (exact - pert) / (exact if exact != 0 else 1.0)
print(f"\nRelative diffs (pert vs exact): Res1={rel_diff(chi_qr_exact,chi_qr_pert):.3f}, Res2={rel_diff(chi_qls_exact,chi_qls_pert):.3f}, Res3={rel_diff(chi_qrs_exact,chi_qrs_pert):.3f}")

In [ ]:
import numpy as np

# Capacitance values (Farads) Hanzhe params 08/21/2025
C_q = 94e-15     # Qubit capacitance
C_r = 3.75e-13      # Resonator 1 capacitance
C_ls = 8.333e-13     # Resonator 2 capacitance
C_rs = 4.5e-13     # Resonator 3 capacitance

# Coupling capacitances (Farads)
C_qr = 6e-15     # Qubit-Resonator 1 coupling
C_qls = 5.29e-15    # Qubit-Resonator 2 coupling
C_qrs = 2.054e-15    # Qubit-Resonator 3 coupling

# Frequencies (rad/s) -- fill in your values
w_q = 3.2e9 # low freq  #MHz      # Qubit frequency
w_r = 6.73e9   # Resonator 1 frequency
w_ls = 3.01e9  # Resonator 2 frequency
w_rs = 5.8e9   # Resonator 3 frequency

alpha = 0.160e9  # Anharmonicity (example value)

# g calculations , g is Jaynes cummings coupling coeff
g_qr = 0.5 * np.sqrt(w_q * C_q) * np.sqrt(w_r * C_r) * (C_qr / (C_q * C_qr + C_q * C_r + C_qr * C_r))
g_qls = 0.5 * np.sqrt(w_q * C_q) * np.sqrt(w_ls * C_ls) * (C_qls / (C_q * C_qls + C_q * C_ls + C_qls * C_ls))
g_qrs = 0.5 * np.sqrt(w_q * C_q) * np.sqrt(w_rs * C_rs) * (C_qrs / (C_q * C_qrs + C_q * C_rs + C_qrs * C_rs))


def g_from_caps(C1, Cg, Cr, Z0=50.0):
    denom = C1*Cg + C1*Cr + Cg*Cr
    e = 1.6e-19
    hbar = 1.0545718e-34
    pref = e * np.sqrt(np.pi * hbar / (2.0 * Z0))
    g_rad = pref * (Cg / denom) / hbar   # g in rad/s (since equation is ħ g = ...)
    g_hz = g_rad / (2*np.pi)
    return g_hz / 1e6  # MHz

g_qr = g_from_caps(C_q, C_qr, C_r)
g_qls = g_from_caps(C_q, C_qls, C_ls)
g_qrs = g_from_caps(C_q, C_qrs, C_rs)

print(f"g_qr = {g_qr:.3f} MHz")
print(f"g_qls = {g_qls:.3f} MHz")
print(f"g_qrs = {g_qrs:.3f} MHz")   


#chi calc




g_qr = 69.281 MHz
g_qls = 27.933 MHz
g_qrs = 20.793 MHz


In [13]:
import scqubits as scq
import qutip as qt
import numpy as np

# device / transmon / resonator params (GHz)
wq_GHz = 5.3
wr_GHz = 6.75
w_ls_GHz = 3.0
w_rs_GHz = 5.5
EC = 0.16
EJ = 22.5

# --- Use g values directly (MHz) - edit these as needed ---
g_qr_MHz  = 69.28
g_qls_MHz = 27.9
g_qrs_MHz = 20.8

def compute_chi_for_resonator(wr_here_GHz, g_MHz, label):
    g_GHz = g_MHz / 1e3  # MHz -> GHz
    # build systems
    tmon = scq.Transmon(EJ=EJ, EC=EC, ng=0, ncut=41, truncated_dim=10)
    resonator = scq.Oscillator(E_osc=wr_here_GHz, truncated_dim=20)
    hs = scq.HilbertSpace([tmon, resonator])

    # add interaction using numeric literal for g (avoid NameError / constants parsing issues)
    g_pref = 1j * g_GHz
    expr = f"{g_pref} * n * a - {g_pref} * n * adag"  # numeric literal inserted into expression
    hs.add_interaction(
        expr=expr,
        op1=("n", tmon.n_operator),
        op2=("adag", resonator.creation_operator),
        op3=("a", resonator.annihilation_operator),
        add_hc=False,
    )

    hs.generate_lookup()

    # build full Hamiltonian and diagonalize (more robust than reading hs['evals'] directly)
    ham_sparse = hs.hamiltonian()
    H_full = 2 * np.pi * qt.Qobj(ham_sparse)
    evals = H_full.eigenenergies()
    # convert to GHz
    evalues_GHz = (evals - evals[0]) / (2 * np.pi)

    # get dressed indices and guard against missing indices
    def safe_get(idx_tuple):
        idx = hs.dressed_index(idx_tuple)
        if idx is None or idx >= len(evalues_GHz):
            raise IndexError(f"dressed index {idx_tuple} -> {idx} out of range")
        return evalues_GHz[idx]

    e_11 = safe_get((1, 1))
    e_10 = safe_get((1, 0))
    e_01 = safe_get((0, 1))
    e_00 = safe_get((0, 0))

    chi_exact_GHz = e_11 - e_10 - e_01 + e_00

    # perturbative dispersive chi (transmon formula)
    Delta_GHz = wq_GHz - wr_here_GHz
    alpha_GHz = -EC
    chi_pert_GHz = 2 * (g_GHz ** 2) * alpha_GHz / (Delta_GHz * (Delta_GHz + alpha_GHz))

    print(f"\n{label}: g = {g_MHz:.3f} MHz | Exact chi = {chi_exact_GHz*1e3:.4f} MHz | Pert chi = {chi_pert_GHz*1e3:.4f} MHz")
    print(f"  Energies (GHz) e11,e10,e01,e00 = {e_11:.6f}, {e_10:.6f}, {e_01:.6f}, {e_00:.6f}")
    print(f"  Δ = {Delta_GHz:.6f} GHz, α = {alpha_GHz:.6f} GHz")
    return chi_exact_GHz, chi_pert_GHz

# compute for all three resonators
chi_qr_exact, chi_qr_pert = compute_chi_for_resonator(wr_GHz, g_qr_MHz, "Resonator 1 (wr)")
chi_qls_exact, chi_qls_pert = compute_chi_for_resonator(w_ls_GHz, g_qls_MHz, "Resonator 2 (w_ls)")
chi_qrs_exact, chi_qrs_pert = compute_chi_for_resonator(w_rs_GHz, g_qrs_MHz, "Resonator 3 (w_rs)")

# relative differences
def rel_diff(exact, pert):
    return (exact - pert) / (exact if exact != 0 else 1.0)

print(f"\nRelative diffs (pert vs exact): Res1={rel_diff(chi_qr_exact,chi_qr_pert):.3f}, Res2={rel_diff(chi_qls_exact,chi_qls_pert):.3f}, Res3={rel_diff(chi_qrs_exact,chi_qrs_pert):.3f}")


Resonator 1 (wr): g = 69.280 MHz | Exact chi = -1.5879 MHz | Pert chi = -0.6579 MHz
  Energies (GHz) e11,e10,e01,e00 = 11.948183, 5.194315, 6.755456, 0.000000
  Δ = -1.450000 GHz, α = -0.160000 GHz

Resonator 2 (w_ls): g = 27.900 MHz | Exact chi = -0.0654 MHz | Pert chi = -0.0506 MHz
  Energies (GHz) e11,e10,e01,e00 = 8.200927, 5.201903, 2.999089, 0.000000
  Δ = 2.300000 GHz, α = -0.160000 GHz

Resonator 3 (w_rs): g = 20.800 MHz | Exact chi = -2.2165 MHz | Pert chi = -1.9228 MHz
  Energies (GHz) e11,e10,e01,e00 = 10.698995, 5.198379, 5.502833, 0.000000
  Δ = -0.200000 GHz, α = -0.160000 GHz

Relative diffs (pert vs exact): Res1=0.586, Res2=0.226, Res3=0.132
